# Generated by Django 2.2.6 on 2019-10-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='  ', max_length=200)),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
