# Generated by Django 2.2.6 on 2019-11-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision_app', '0002_auto_20191111_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
