# Generated by Django 2.2.6 on 2019-11-11 10:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision_app', '0004_auto_20191111_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='quantity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
