# Generated by Django 2.2.6 on 2019-11-11 10:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision_app', '0005_auto_20191111_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
