# Generated by Django 2.2.6 on 2019-11-11 13:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision_app', '0006_auto_20191111_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='goods',
            name='quantity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
